# .air.toml - Configuration for air, a live-reloader for Go applications.
# https://github.com/cosmtrek/air

# Working directory
root = "."
# Temporary directory for the binary
tmp_dir = "jules-scratch"

[build]
  # Command to build the application
  cmd = "go build -o ./jules-scratch/k2ray ./cmd/k2ray/main.go"
  # The binary to run
  bin = "jules-scratch/k2ray"
  # Additional arguments for running the binary
  full_bin = "APP_ENV=dev ./jules-scratch/k2ray"

  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these directories
  exclude_dir = ["assets", "jules-scratch", "vendor", "web/node_modules"]
  # Log file for the build process
  log = "air-build.log"
  # Delay in milliseconds before rebuilding
  delay = 1000
  # Stop the running app on build error
  stop_on_error = true

[log]
  # Show timestamps in logs
  time = true

[color]
  # Customize colors for different parts of the output
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  # Clean up the temp directory on exit
  clean_on_exit = true